List tiposBandeirasCartoes = [
  {'nome': 'Mastercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/mastercard.png'},
  {'nome': 'Visa', 'taxa': 0, 'ativo': true , 'imagem': 'assets/visa.png'},
  {'nome': 'Hipercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/hipercard.png'},
  {'nome': 'Elo', 'taxa': 0, 'ativo': true , 'imagem': 'assets/elo.png'},
  {'nome': 'Banese Card', 'taxa': 0, 'ativo': true , 'imagem': 'assets/banese.png'},
  {'nome': 'American Express', 'taxa': 0, 'ativo': true , 'imagem': 'assets/american_express.png'},
  {'nome': 'Diners Club', 'taxa': 0, 'ativo': true , 'imagem': 'assets/diners_club.png'},
  {'nome': 'Sodexo Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/sodexo.png'},
  {'nome': 'Vr Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vr.jpeg'},
  {'nome': 'Vr Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vr.jpeg'},
  {'nome': 'Ticket Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/ticket.png'},
  {'nome': 'Ticket Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/ticket.png'},
  {'nome': 'Alelo Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/alelo.png'},
  {'nome': 'Alelo Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/alelo.png'},
  {'nome': 'Vale Gás', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vale_gas.png'},
];
List tiposBandeirasCartoesCredito = [
  {'nome': 'Mastercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/mastercard.png'},
  {'nome': 'Visa', 'taxa': 0, 'ativo': true , 'imagem': 'assets/visa.png'},
  {'nome': 'Hipercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/hipercard.png'},
  {'nome': 'Elo', 'taxa': 0, 'ativo': true , 'imagem': 'assets/elo.png'},
  {'nome': 'Banese Card', 'taxa': 0, 'ativo': true , 'imagem': 'assets/banese.png'},
  {'nome': 'American Express', 'taxa': 0, 'ativo': true , 'imagem': 'assets/american_express.png'},
  {'nome': 'Diners Club', 'taxa': 0, 'ativo': true , 'imagem': 'assets/diners_club.png'},
];
List tiposBandeirasTodos = [
  {'nome': 'Mastercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/mastercard.png'},
  {'nome': 'Visa', 'taxa': 0, 'ativo': true , 'imagem': 'assets/visa.png'},
  {'nome': 'Hipercard', 'taxa': 0, 'ativo': true , 'imagem': 'assets/hipercard.png'},
  {'nome': 'Elo', 'taxa': 0, 'ativo': true , 'imagem': 'assets/elo.png'},
  {'nome': 'Banese Card', 'taxa': 0, 'ativo': true , 'imagem': 'assets/banese.png'},
  {'nome': 'American Express', 'taxa': 0, 'ativo': true , 'imagem': 'assets/american_express.png'},
  {'nome': 'Diners Club', 'taxa': 0, 'ativo': true , 'imagem': 'assets/diners_club.png'},
  {'nome': 'Sodexo Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/sodexo.png'},
  {'nome': 'Vr Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vr.jpeg'},
  {'nome': 'Vr Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vr.jpeg'},
  {'nome': 'Ticket Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/ticket.png'},
  {'nome': 'Ticket Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/ticket.png'},
  {'nome': 'Alelo Alimentação', 'taxa': 0, 'ativo': true , 'imagem': 'assets/alelo.png'},
  {'nome': 'Alelo Refeição', 'taxa': 0, 'ativo': true , 'imagem': 'assets/alelo.png'},
  {'nome': 'Vale Gás', 'taxa': 0, 'ativo': true , 'imagem': 'assets/vale_gas.png'},
];
