name: delivery
description: Delivery App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #LOGINS
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.3+1
  sign_button: ^2.0.0
  sms_advanced: ^1.0.1
  #FIM LOGINS

  #FIREBASE
  firebase_storage: ^9.0.0
  cloud_firestore: ^2.3.0
  firebase_core: ^1.3.0
  firebase_auth: ^3.1.4
  firebase_messaging: ^11.2.4
  #FIM FIREBASE

  #GETTERS
  flutter_local_notifications: ^9.0.0-dev.2
  image_picker: ^0.8.3+2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  image_cropper: ^1.4.1
  speech_to_text: ^5.0.0
  file_picker: ^4.0.0
  qr_code_tools: ^0.0.7
  flutter_secure_storage: ^4.2.1
  permission_handler: ^8.3.0
  #FIM GETTERS

  #WIDGETS
  flutter_spinkit: ^5.1.0
  progress_dialog: ^1.2.2
  fluttertoast: ^8.0.3
  avatar_glow: ^2.0.1
  curved_navigation_bar: ^1.0.1
  flutter_masked_text2: ^0.9.1
  pin_code_fields: ^7.3.0
  #FIM WIDGETS

  cupertino_icons: ^1.0.2
  mdi: ^5.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  bloc_pattern: ^3.0.0
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  dio: ^4.0.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true